Repository vapor/websocket-kit, pull requests merged in 2018-10, with the labels that each got.

#25 Data Framing support (RFC section 5)
  Sources/WebSocket/WebSocketHandler.swift
Labels: enhancement

#24 Masking `pong` and `close` frames
  Sources/WebSocket/WebSocketHandler.swift
Labels: bug

#20 Set WebSocketFrame's mask key parameter
  Sources/WebSocket/WebSocket.swift
Labels: enhancement

#17 Flush channel after writing close and ping frames. Fixes #14
  Sources/WebSocket/WebSocketHandler.swift
Labels: bug

#28 1.1
  Sources/WebSocket/WebSocket.swift
  Sources/WebSocket/WebSocketFrameSequence.swift
  Sources/WebSocket/WebSocketHandler.swift
  Tests/WebSocketTests/WebSocketTests.swift
Labels: bug, enhancement
