Repository vapor/websocket-kit, pull requests merged in 2019-12, with the labels that each got.

#48 Fix default wss:// port
  Sources/WebSocketKit/WebSocket+Connect.swift
  Tests/WebSocketKitTests/NIOWebSocketClientTests.swift
Labels: bug

#50 beta.2
  .github/FUNDING.yml
  .github/workflows/test.yml
  Package.swift
  Tests/LinuxMain.swift
  Tests/WebSocketKitTests/NIOWebSocketClientTests.swift
  Tests/WebSocketKitTests/XCTestManifests.swift
Labels: enhancement

#45 Add ping/pong callbacks to WebSocket
  Sources/WebSocketKit/HTTPInitialRequestHandler.swift
  Sources/WebSocketKit/WebSocket.swift
  Sources/WebSocketKit/WebSocketClient.swift
  Tests/WebSocketKitTests/NIOWebSocketClientTests.swift
Labels: enhancement, semver-minor
