Repository vapor/websocket-kit, pull requests merged in 2022-06, with the labels that each got.

#115 Rewrite some really truly amazingly darn outdated CI
  .github/workflows/main-codecov.yml
  .github/workflows/test.yml
Labels: enhancement

#114 Make sure onPing is called and account for control frames being able to be interspersed with message fragments
  Sources/WebSocketKit/WebSocket.swift
  Tests/WebSocketKitTests/WebSocketKitTests.swift
Labels: bug, semver-patch

#118 Enable compilation on iOS
  Package.swift
Labels: semver-minor
